### ISSUE TITLE
Multiline snippet description when converting to SnipMate

### ISSUE THREAD

**Issue by dcampos** [smjonas/snippet-converter.nvim#3]
When trying to convert snippets (like [this one](https://github.com/rafamadriz/friendly-snippets/blob/974d79269a5a7f63e973db6a51b081a45750d026/snippets/plantuml.json#L55)) from [rafamadriz/friendly-snippets](https://github.com/rafamadriz/friendly-snippets) to SnipMate, some snippets containing `\n` in their description aren't being converted correctly. This is a minimal example snippet (not from friendly-snippets):

```json
{
  "foreach": {
    "prefix": "foreach",
    "body": ["for (${1:type} ${2:var} : ${3:iterable}) {", "\t$0", "}"],
    "description": "Enhanced for loop\nThis is a new line\nAnd another one"
  }
}
```
Converted (the description spans multiple lines):

```vim-snippet
# Generated by snippet-converter.nvim (https://github.com/smjonas/snippet-converter.nvim)

snippet foreach Enhanced for loop
This is a new line
And another one
	for (${1:type} ${2:var} : ${3:iterable}) {
		$0
	}
```

One possible solution would be converting newlines to spaces.

**Comment by smjonas** [comment]
Thanks for reporting!
